const routes = {
  home: '/',
  scanner:'/scanner',
  contract:'/create-contract',
  listContract:'/list-contract',
  nft:'/create-nft',
  viewCert:'/view-cert?',
  viewNft:'/view-contract?',
  livePricing: '/live-pricing',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  search: '/search',
  notification: '/notifications',
  vote: '/vote',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  signIn: '/authentication',
  signUp: '/authentication/sign-up',
  resetPin: '/authentication/reset-pin',
  forgetPassword: '/authentication/forget-password',
  pages: '/pages',
};

export default routes;
